<a href="https://colab.research.google.com/github/mainak8967/MACHINE_LEARNING/blob/main/MatrixInPython.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
#Creating Matrix using array

In [3]:
matrix_1=np.asarray([[2,3],[4,6]])

In [4]:
matrix_1

array([[2, 3],
       [4, 6]])

In [5]:
matrix_1.shape

(2, 2)

In [7]:
matrix_2=np.array([[10,20,30],[2,3,4],[5,6,7]])
matrix_2

array([[10, 20, 30],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [8]:
matrix_2.shape

(3, 3)

Creating Matrix With random values

In [9]:
random_matrix=np.random.rand(3,3)
random_matrix

array([[0.16698378, 0.89330547, 0.13838827],
       [0.7463804 , 0.26115583, 0.52711293],
       [0.73762123, 0.03763668, 0.02337359]])

In [10]:
#creating matrix with random integers
r=np.random.randint(100,size=(4,5))#x is from 0 to 100-1
r

array([[ 4, 74, 99, 44, 57],
       [98, 25, 50, 53, 14],
       [30, 16, 33, 82, 46],
       [88,  6, 44, 21, 86]])

Matrix with all values as 1

In [11]:
matrix_3=np.ones((2,3))
matrix_3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
#the values were of float type gotcha convert to int
matrix_3=np.ones((2,3),dtype=int)
matrix_3

array([[1, 1, 1],
       [1, 1, 1]])

Null Matrix

In [14]:
null_matrix=np.zeros((4,4))
null_matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Identity Matrix

In [15]:
identity_matrix=np.eye(3,3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Transpose of a Matrix

In [16]:
a=np.random.randint(10,size=(2,3))
a

array([[4, 8, 3],
       [2, 5, 2]])

In [17]:
b=np.transpose(a)
b

array([[4, 2],
       [8, 5],
       [3, 2]])

In [18]:
b.shape

(3, 2)

Matrix Addition-only possible for two similar matrices(same size)

In [21]:
a+matrix_3

array([[5, 9, 4],
       [3, 6, 3]])

In [22]:
#a+b will be erronius

Matrix Subtraction for similar matrices

In [23]:
a-matrix_3

array([[3, 7, 2],
       [1, 4, 1]])

Multiplication of matrix with scalar

In [24]:
3*a

array([[12, 24,  9],
       [ 6, 15,  6]])

In [25]:
np.multiply(a,3)

array([[12, 24,  9],
       [ 6, 15,  6]])

Multiplication of matrix with another compatible matrix

In [29]:
p=np.dot(a,b)
p

array([[89, 54],
       [54, 33]])

In [30]:
p.shape

(2, 2)